### ISSUE TITLE
Không đính kèm giấy phép nguồn mở sử dụng trong mã nguồn

### ISSUE THREAD

**Issue by baonq-me** [olp-dtu-2024/DTU-GreenHope#35]
Không đính kèm giấy phép nguồn mở sử dụng trong mã nguồn

https://github.com/olp-dtu-2024/DTU-GreenHope/blob/5b956c8dc532d6e9b056520311b3450adf6ee3b2/captcha-service/configs.py#L1

**Comment by auroraphtgrp01** [comment]
Dạ em cảm ơn lời nhắc nhở của ban giám khảo ạ. Vì lần đầu làm mã nguồn mở nên còn nhiều thiếu xót, mong ban tổ chức thông cảm ạ. Chúng em sẽ nhanh chóng bổ sung ạ.
